### ISSUE TITLE
Disky is constantly Crashing in background

### ISSUE THREAD

**Issue by materialred** [newhinton/disky#24]
```FATAL EXCEPTION: main
Process: de.felixnuesse.disky, PID: 7829
java.lang.RuntimeException: Unable to start service de.felixnuesse.disky.background.ScanService@14fca6f with null: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service de.felixnuesse.disky/.background.ScanService
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5053)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2390)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service de.felixnuesse.disky/.background.ScanService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5019)
	at android.os.Parcel.readParcelable(Parcel.java:5001)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3181)
	at android.os.Parcel.createException(Parcel.java:3170)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.os.Parcel.readException(Parcel.java:3095)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6896)
	at android.app.Service.startForeground(Service.java:862)
	at de.felixnuesse.disky.background.ScanService.onStartCommand(ScanService.kt:81)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5035)
	... 9 more```

Version: 1.1.0
Device: Google Pixel 8 Pro
Rom: crDroid 10.5 (Android 14)

**Comment by newhinton** [comment]
Does crDroid impose any restrictions about background work? Do you have notifications enabled?
