### ISSUE TITLE
Stuck at 92%

### ISSUE THREAD

**Issue by SamuXzX** [newhinton/disky#28]
Every time I try to do a scan, the progress bar get stuck at 92%. I waited for a long time but it doesn't keep going.
I don't know how to provide a log.

- Android 11
- Motorola Moto G 5G plus
- Disky 1.1.0

**Comment by SamuXzX** [comment]
Last check, stuck at 89%.

**Comment by newhinton** [comment]
Without logs, this will be hard to diagnose? Are you willing to create them? (You'd need to install either adb-tools or android studio, the latter is usually more easy)

**Comment by KoolTechTricks** [comment]
I can get into this stuck state at first launch after installing the app. Also, it stucks when device's theme is changed (from light to dark or vice versa) while the app is opened and showing folders.

I think this scanning screen is fake. There's a notification, which indicates scanning status. Normally, it disappears when scanning is finished. In the stuck state, notification also disappears, but scanning animation isn't.

I always get the same percent on the same device, but the other on the different device.

Rescanning didn't help get out from the stuck state, only restarting the app helps.

**Comment by newhinton** [comment]
> I think this scanning screen is fake.

I mean, yeah, its just a screen that is shown when there is nothing to show because either the data is outdated or not initially scanned.

When the scan-service is done, it notifies the main app, which shows the proper data. Getting stuck usually means the scan-service encountered an error.

I dont yet have good error-handling in place, so it might get stuck without an error.


The theme-switching however is different, i just didn't fix it yet.


To actually fix your specific issues however, i need logs. It would be very helpful if you could provide a logcat snippet of the crash.

@KoolTechTricks Are you on Android 11 aswell?

**Comment by KoolTechTricks** [comment]
I'm reinstalling the app many times on Android 11 and 13. Android 11 always fails to scan at the first launch (83%), while Android 13 sometimes fails (59%), sometimes not.

My issue probably isn't caused by something that caused OP's issue. But I believe there are other cases when this stuck happens.

The app indeed should have the ability to view logs.

**Comment by Qronikarz** [comment]
Joining to say that at first boot I had the internal memory stuck at 54% no matter how many reloads inside. SD card worked without problems though (the only issue was the progress bar showed 2183443% for a while, but it finished quickly)

After force closing the app it finished the internal memory scan. Lineage OS 20.

+1 for ability to view logs

**Comment by SamuXzX** [comment]
> Without logs, this will be hard to diagnose? Are you willing to create them? (You'd need to install either adb-tools or android studio, the latter is usually more easy)

I'm absolutely willing to, I just don't know how. Could you guide me on which adb commands I have to launch?
Or maybe to the page where you already explain it: I may have missed it.

**Comment by newhinton** [comment]
[disky-release-v1.2.0.zip](https://github.com/user-attachments/files/16118598/disky-release-v1.2.0.zip)

You can try above apk. It contains a notification that shows up when an exception is encountered in the scan service. That should containt the actual stacktrace, that i need. It is signed with the same release key, so you can just download and install it over the f-droid variant.

**Comment by SamuXzX** [comment]
I installed the apk, but the app didn't got stuck, so I don't have any stacktrace to give you 😅

**Comment by Qronikarz** [comment]
I have tried the .apk and this time it got stuck at 45%, but you see the problem is that the scan is just stuck. There's no exception, no error, nothing. So the notification doesn't show at all. Naturally force-closing the app worked again, but this time I couldn't scan the SD card at all.

**Comment by newhinton** [comment]
> So the notification doesn't show at all. 

No notification? Not even the "Scan in Progress"-notification? Did you grant access to notifications for this app?

If yes, you will have to capture a log manually via android studio/adb.

**Comment by EmpireMatrix** [comment]
I had a similar problem after the first launch, the scan got stuck at 58%. I force closed the app and then it went quick and smooth. Seems to be a problem on the loading screen...
Logs would be very welcomed 
Thanks for your work dude, the app is really nice and handy when it works 👍

**Comment by floviolleau** [comment]
Hi,

Thanks for this beautiful open source app!

Same issue here. The version from F-droid is not working and stuck at 89% but the version in this thread IS working.

Device: samsung Galaxy tab A9+ SM-X210.

No notifications with the version in this thread.

Cheers

**Comment by newhinton** [comment]
@floviolleau Can you try to grant all battery exemptions for the tablet and try again? If the process gets stuck without any kind of notification this might be an issue with the service itself

**Comment by floviolleau** [comment]
Hi,

Hard to say. I uninstalled the version of this thread.
I reinstalled the version from F-droid and I set battery mod to unrestricted and seems to be less buggy.

If I play with it, killing, restarting, refresh scan from the app, I can sometimes be stuck to 90% but less frequently.

Kind regards

**Comment by newhinton** [comment]
Good news, i think i have a lead why it doesn't work. Until now i was expecting that there is an issue with the actual scanner, but i think after the scan finishes, the animation is stuck on top of the list. There is probably a racecondition that i now need to find.

**Comment by newhinton** [comment]
This bug is truly astonishing. I have no clue why it happens, and how to reliably debug this.

Sometimes it happens with my debug builds, but the next build will be fine and so on. I'll keep you updated when i nake progress on this one.

**Comment by phatal** [comment]
> [disky-release-v1.2.0.zip](https://github.com/user-attachments/files/16118598/disky-release-v1.2.0.zip)
> 
> You can try above apk. It contains a notification that shows up when an exception is encountered in the scan service. That should containt the actual stacktrace, that i need. It is signed with the same release key, so you can just download and install it over the f-droid variant.

I  had same issue as others (stuck at 89%). But version installed from this archive works well now.

**Comment by SilverGreen93** [comment]
I have the same issue with version 1.3.2 on Android 16.

The scan notification shows until progress reaches 89%, then the notification disappears and the scan never finishes.

**Comment by newhinton** [comment]
[disky-prerelease-v2.0.0.zip](https://github.com/user-attachments/files/26285919/disky-prerelease-v2.0.0.zip)

@SilverGreen93 Can you try this new build?

I still have the reproducibility issue, but i added even more error handling. (2.0.0 will also be a lot faster, depending on your device up to 4 times)

**Comment by SilverGreen93** [comment]
> [disky-prerelease-v2.0.0.zip](https://github.com/user-attachments/files/26285919/disky-prerelease-v2.0.0.zip)
> 
> @SilverGreen93 Can you try this new build?
> 
> I still have the reproducibility issue, but i added even more error handling. (2.0.0 will also be a lot faster, depending on your device up to 4 times)

Thanks! I tried it more than a couple of times and it is indeed way faster and does not hang at all. Seems that it is fixed for me. 👍

**Comment by newhinton** [comment]
I started the release of v2. It should show up on fdroid in the next few days.

If i don't recieve complaints about stuck scans in a few weeks, i will close this ticket. If this ticket is closed, but you get stuck with 2.0.0 anyway, please comment.

**Comment by leoossa** [comment]
@newhinton i have issue with aborted scanning:

`java.lang.NullPointerException: Attempt to get length of null array
	at java.security.MessageDigest.update(MessageDigest.java:372)
	at java.security.MessageDigest.digest(MessageDigest.java:447)
	at java.util.UUID.nameUUIDFromBytes(UUID.java:169)
	at de.felixnuesse.disky.extensions.StorageVolumeKt.getStorageUUID(storageVolume.kt:21)
	at de.felixnuesse.disky.scanner.AppScanner.scanApps(AppScanner.kt:49)
	at de.felixnuesse.disky.scanner.Scanner.scan(Scanner.kt:65)
	at de.felixnuesse.disky.background.ScanService$onStartCommand$1.invokeSuspend(ScanService.kt:75)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
`  

v.2.0.1 F-Droid version

**Comment by newhinton** [comment]
Are you scanning the sdcard or primary?
What device, android version and/or rom are you using?

**Comment by SilverGreen93** [comment]
> If i don't recieve complaints about stuck scans in a few weeks, i will close this ticket. If this ticket is closed, but you get stuck with 2.0.0 anyway, please comment.

Unfortunately the version v2.0.1 from Fdroid is broken entirely. The scan shows only 0% and then all sizes are 0.

| --- | --- |
| --- | --- |
| ![Screenshot_2026-04-18-21-26-53-447_de.felixnuesse.disky.jpg](https://github.com/user-attachments/assets/4b5498fd-5205-4b81-b864-74d3208f73db) | ![Screenshot_2026-04-18-21-27-02-440_de.felixnuesse.disky.jpg](https://github.com/user-attachments/assets/f5d7d5b2-5394-4e80-9e46-c70e73a5f742) |

**Comment by newhinton** [comment]
> Are you scanning the sdcard or primary? What device, android version and/or rom are you using?

I need more information.

**Comment by SilverGreen93** [comment]
I think the issue both I and @leoossa are having is with permissions.

I just cleared all data for the application, restarted it and it asked for permissions, then all worked fine.

It is curious why the app never asked for permission when first installing version 2.0.1 (I had no previous app install, it was not an update, as I uninstalled the test version you provided some time ago before installing this one.)

**Comment by newhinton** [comment]
Ah, you are right, i can reproduce the issue.

You somehow lost the permission to access all files. If you reenable that, the app will work as expected again.

I will implement better permission handling tomorrow and publish a 2.1

By the way before someone comments about that:
It is known that the overall calculation of filesizes is broken on 2.0.1. That has been fixed and will come with 2.1.

**Comment by newhinton** [comment]
2.1 has just been released. In a few days it should show up on f-droid aswell.

**Comment by SilverGreen93** [comment]
> 2.1 has just been released. In a few days it should show up on f-droid aswell.

I can confirm this fixes all my issues. Good job! Thank you!
